<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByFeatured(){
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
        SELECT u
        FROM AppBundle:Post u
        WHERE u.category = :featured');
        $consulta->setParameter('featured', featured);

        try{
            return $consulta->getSingleResult();
        }catch (\Exception $error){
            return false;
        }
    }

    public function findBylimit($limit){
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
        SELECT u
        FROM AppBundle:Post u');
        $consulta->setMaxResults($limit);

        try{
            return $consulta->getResult();
        }catch (\Exception $error){
            return false;
        }
    }

    public function findByTitle($slug,$id){
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
        SELECT u
        FROM AppBundle:Post u
        WHERE u.slug = :slug
        AND u.id=:id');
        $consulta->setParameter('slug', $slug);
        $consulta->setParameter('id',$id);

        try{
            return $consulta->getSingleResult();
        }catch (\Exception $error){
            return false;
        }
    }
}
