<?php

namespace AppBundle\Repository;

/**
 * PostCommentNotLoginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostCommentNotLoginRepository extends \Doctrine\ORM\EntityRepository
{
}
