<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByPerson($person){
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
        SELECT u
        FROM AppBundle:User u
        WHERE u.person = :person');
        $consulta->setParameter('person', $person);
        try{
           return $consulta->getSingleResult();
        }catch (\Exception $error){
            return false;
        }
    }

    public function findByEmail($mail){
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
        SELECT u
        FROM AppBundle:User u
        WHERE u.email = :email');
        $consulta->setParameter('email', $mail);
        try{
            return $consulta->getSingleResult();
        }catch (\Exception $error){
            return false;
        }
    }
}
