# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        usuarios:
            entity: { class: AppBundle\Entity\User, property: email }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        frontend:
            pattern:        ^/*
            provider:       usuarios
            anonymous:      ~
            form_login:
                login_path: user_login
                check_path: user_login_check
            logout:
                path:       user_logout
            remember_me:
                secret:     cibermania123
                lifetime:   604800  # 604.800 = 3.600 * 24 * 7 = 1 semana
    access_control:
            - { path: ^/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    encoders:
            AppBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]